services:
  - type: web
    name: evai-mvp-web
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: PORT
        value: "10000"
    healthCheckPath: /api/health
